### ISSUE TITLE
Breakpoint indicators in overview ruler do not follow specified color

### ISSUE THREAD

**Issue by SoloWingPixy2097** [ericgomez/vscode-breakpoint-highlight#1]
As the title describes

When setting the VSCode option (user settings):
    `"debug.showBreakpointsInOverviewRuler": true`

The indicator in the overview ruler (scrollbar map) does not take on the same color as specified by this extension

It would be nice if those indicators could also adapt to the selected color.
Because by default these breakpoint indicator colors are red, the same as error indicators

Thanks!

**Comment by ericgomez** [comment]
Currently, the extension customizes only the line of the breakpoint, not the indicator in the overview ruler. However, in VS Code, there's an existing setting that allows you to change the icon color specifically:

```
"workbench.colorCustomizations": {
    "debugIcon.breakpointForeground": "#ffff00"
}
```

This configuration lets you set a custom color for the breakpoint icon, so it can stand out differently from error indicators.

I hope this helps clarify the customization options available.
Thanks for the feedback!

**Comment by SoloWingPixy2097** [comment]
Oh sorry, I wasn't aware of that setting, but can confirm that does indeed solve my issue, thank you!
